const ItemcardData ={
    mainCourse : [
    {
        id : 1,
        title : 'Chole-Chawal',
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/cholechawal.jpg' ,
    },
    {
        id : 2,
        title :'Rajma-Rice' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : 'images/RajmaRice.jpg',
    },
    {
        id : 3,
        title :'Fried-Rice' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : 'images/friedRice.jpg',
    },
],
    beverages : [
    {
        id : 1,
        title : 'Thums Up',
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : 'images/ThumsUp.webp',
    },
    {
        id : 2,
        title : 'Sprite',
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Sprite.jpg',
    },
    {
        id : 3,
        title : 'Monster' ,
        price : 100,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Monster.jpg',
    },
    {
        id : 4,
        title : 'Maaza',
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Maaza.jpg',
    },
    {
        id : 5,
        title : 'Limca' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Limca.jpeg',
    },
    {
        id : 6,
        title : 'Coke' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Coke.jpg',
    },
    {
        id : 7,
        title : 'Cold Coffee' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/ColdCoffee.avif',
    },
    {
        id : 8,
        title : 'Hot Coffee' ,
        price : 20,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Coffee.jpg',
    },
    {
        id : 9,
        title : 'Special Tea' ,
        price : 10,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/chai.jpg',
    },
],
    fastFood : [
    {
        id : 1,
        title : 'Chole Bhature' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/choleBhature.jpeg',
    },
    {
        id : 2,
        title : 'Chole Kulche',
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Cholekulche.jpeg',
    },
    {
        id : 3,
        title : 'French Fries' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/frenchfries.jpg',
    },
    {
        id : 4,
        title : 'Momos' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Momos.jpg',
    },

    {
        id : 5,
        title :'Fried Momos' ,
        price : 50,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/FriedMomos.jpg',
    },
    {
        id : 6,
        title :'Noodles' ,
        price : 40,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/noodles.jpg',
    },
    {
        id : 7,
        title :'Samosa ' ,
        price : 10,
        info :'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/Samosa.jpg',
    },
],
    wafers : [
        {
        id : 1,
        title : 'Haldirams Chips',
        price : 15,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/haldiramgreen.webp',
    },
 {
        id : 2,
        title : 'Haldirams Chips' ,
        price : 15,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : 'images/haldirambue.webp',
    },
    {
        id : 3,
        title : 'Haldirams Aloo Bhujiya',
        price : 10,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/alooBhujiya.jpeg',
    },
    {
        id : 4,
        title : 'Lays' ,
        price : 15,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/BlueLays.jpeg',
    },
    {
        id : 5 ,
        title : 'Lays' ,
        price : 15,
        info : 'Lorem ipsum dolor sit amet.',
        imgsrc : '/images/GreenLays.webp',
    },
]
}
export default ItemcardData